In [14]:
import glob
import os
import time 
import numpy as np


import cv2
from scipy import ndimage

import slicer
import Elastix
import JupyterNotebooksLib as slicernb

import sitkUtils as su
import SimpleITK as sitk


In [15]:
root_dir = 'E:\\Test_data_set'
mni_path = 'C:\\Users\\User\\AppData\\Local\\NA-MIC\\Slicer 4.11.20200930\\mni_icbm152_t1_tal_nlin_asym_09a.nii'

In [16]:
sub_path_list = sorted(glob.glob(root_dir)) 

In [17]:
sub_path_list

['E:\\Test_data_set']

In [18]:
def load_nii(path):
    """Load dicom files to sitk image"""
    reader = sitk.ImageFileReader()
    reader.SetImageIO("NiftiImageIO")
    reader.SetFileName(path)
    image = reader.Execute()
    
    return image

In [19]:
def registration_elastix(fixedVolumeNode, movingVolumeNode):
    """Ridgid registration Elastix"""
    
    #Set Parmeter
    elastixLogic = Elastix.ElastixLogic()
    parameterFilenames = elastixLogic.getRegistrationPresets()[0][Elastix.RegistrationPresets_ParameterFilenames]

    outputVolumeNode = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLScalarVolumeNode")
    outputTransformNode = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLTransformNode")

    regi =  elastixLogic.registerVolumes(fixedVolumeNode, movingVolumeNode, parameterFilenames = parameterFilenames,
                                         outputVolumeNode =  outputVolumeNode, outputTransformNode = outputTransformNode )
    return outputVolumeNode, outputTransformNode
        
        
#     if (slicer.util.getNode("register_tmp") == None):
#         outputVolumeNode = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLScalarVolumeNode").SetName("register_tmp")
#     else:5 -
#          outputVolumeNode = slicer.util.getNode("register_tmp")
    
    #Execute 
  

In [20]:
def write_nii(image, path):
    """Write medical image to nii"""
    sitk.WriteImage(image, path)

In [21]:
def rescaleIntentsity(image, min_intensity , max_intensity ):
    """Rescale Image intensity range of [min , max]"""
    return sitk.RescaleIntensity(image, min_intensity, max_intensity)

In [22]:
def TransformMarkups(transformNode):    
#     originalFidNode=slicer.mrmlScene.AddNewNodeByClass("vtkMRMLMarkupsFiducialNode")

    
    markupsNode = slicer.mrmlScene.AddNewNodeByClass('vtkMRMLMarkupsFiducialNode')
#     markupsNode.AddControlPoint(vtk.vtkVector3d(0, -1, -1)) #AC
#     markupsNode.AddControlPoint(vtk.vtkVector3d(0, -23, 0 )) #PC
    markupsNode.AddControlPoint(vtk.vtkVector3d(8, -73.0, 19.0)) #V1
    markupsNode.AddControlPoint(vtk.vtkVector3d(37, -13.0, 51.0 )) #M1
  #  markupsNode.AddControlPoint(vtk.vtkVector3d(42, -20.0, 48.0 )) #S1
    markupsNode.AddControlPoint(vtk.vtkVector3d(5.0, 14.0, 47))  #Dosal_ACC +  up5
    markupsNode.AddControlPoint(vtk.vtkVector3d(12, -15, 18.0))  #Thalamus
#     markupsNode.AddControlPoint(vtk.vtkVect|or3d(5.0, 14.0, 57.0))  #Dorsal_ACC +  up15
#     markupsNode.AddControlPoint(vtk.vtkVector3d(5.0, -10.0, 51.0)) #Caudal_ACC
#     markupsNode.AddControlPoint(vtk.vtkVector3d(5.0, -10.0, 56.0)) #Caudal_ACC + up5
#     markupsNode.AddControlPoint(vtk.vtkVector3d(5.0, -10.0, 61.0)) #Caudal_ACC + up15
    
#     markupsNode.AddControlPoint(vtk.vtkVector3d(8, -73.0 - 5, 19.0)) #V1 _5
#     markupsNode.AddControlPoint(vtk.vtkVector3d(37, -13.0, 51.0 + 5)) #M1 _ 5
#     markupsNode.AddControlPoint(vtk.vtkVector3d(42, -20.0, 48.0 + 5)) #S1 _ 5
    
    markupsNode.SetAndObserveTransformNodeID(transformNode.GetID())
#    slicer.modules.transforms.logic().CreateDisplacementVolumeFromTransform(transformNode, markupsNode, False)
    narray = slicer.util.arrayFromMarkupsControlPoints(markupsNode, world=True)
    
    print(narray)
    slicer.mrmlScene.RemoveNode(markupsNode)
    return narray

In [23]:
scene = slicer.mrmlScene
sub_path_list = sorted(glob.glob(os.path.join(root_dir, 'S*')))
print(len(sub_path_list))
i=0

19


In [24]:
sub_path_list

['E:\\Test_data_set\\S30', 'E:\\Test_data_set\\S31', 'E:\\Test_data_set\\S32', 'E:\\Test_data_set\\S33', 'E:\\Test_data_set\\S35', 'E:\\Test_data_set\\S36', 'E:\\Test_data_set\\S38', 'E:\\Test_data_set\\S39', 'E:\\Test_data_set\\S42', 'E:\\Test_data_set\\S43', 'E:\\Test_data_set\\S44', 'E:\\Test_data_set\\S46', 'E:\\Test_data_set\\S47', 'E:\\Test_data_set\\S51', 'E:\\Test_data_set\\S54', 'E:\\Test_data_set\\S55', 'E:\\Test_data_set\\S56', 'E:\\Test_data_set\\S57', 'E:\\Test_data_set\\S58']

In [25]:
scene = slicer.mrmlScene
sub_path_list = sorted(glob.glob(os.path.join(root_dir, 'S*')))
print(len(sub_path_list))
i=0

mni_image = load_nii(mni_path)
MNI_node = su.PushVolumeToSlicer(mni_image)

for sub_path in sub_path_list:
    try:
        sub_name = sub_path.split("\\")[-1].split("_")[0]
       
        print(i)
        i+=1

        T1_path = glob.glob(os.path.join(sub_path, '*crop_T1.nii'))[0]
        T1_image = load_nii(T1_path)
        print('load dicom', T1_path) 

        #sitk image to VolumeNode
        T1_node = su.PushVolumeToSlicer(T1_image)
        print('push image to volumenode')

        MNI_registeredNode, MNI_transformNode = registration_elastix(T1_node , MNI_node)
        print('mni-registration')
        
        target_np = TransformMarkups(MNI_transformNode)

        sub_name = sub_path.split("\\")[-1].split("_")[0]
        save_path = os.path.join(sub_path)

        if not os.path.exists(save_path):
            os.makedirs(save_path)
            print(save_path)
            
            
        V1 = str('{:.3f}'.format(target_np[0][0]) + ' {:.3f}'.format(target_np[0][1]) + ' {:.3f}'.format(target_np[0][2]))
        f = open(os.path.join(save_path, 'target_V1_MNI.txt'), 'w')
        f.write(V1)
        f.close()
               
        M1 = str('{:.3f}'.format(target_np[1][0]) + ' {:.3f}'.format(target_np[1][1]) + ' {:.3f}'.format(target_np[1][2]))
        f = open(os.path.join(save_path, 'target_M1_MNI.txt'), 'w')
        f.write(M1)

        
        Dorsal_ACC = str('{:.3f}'.format(target_np[2][0]) + ' {:.3f}'.format(target_np[2][1]) + ' {:.3f}'.format(target_np[2][2]))
        f = open(os.path.join(save_path, 'target_DorsalACCUp5.txt'), 'w')
        f.write(Dorsal_ACC)
        f.close()

        Thalamus = str('{:.3f}'.format(target_np[3][0]) + ' {:.3f}'.format(target_np[3][1]) + ' {:.3f}'.format(target_np[3][2]))
        f = open(os.path.join(save_path, 'target_Thalamus.txt'), 'w')
        f.write(Thalamus)
        f.close()

        
        print('save target mni to native space')

        #clear

        slicer.mrmlScene.RemoveNode(T1_node)
        slicer.mrmlScene.RemoveNode(MNI_transformNode)
        slicer.mrmlScene.RemoveNode(MNI_registeredNode)
        
        
    except Exception as e: 
        print(e)
        print(sub_path, 'wrong')
        continue

19
0
load dicom E:\Test_data_set\S30\S30_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_182951_957
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_182951_957\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_182951_957\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_182951_957\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node Node
Show volume rendering of node Node_1
Show volume rendering of node Volume


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_182951_957\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_182951_957\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_182951_957\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[  6.15336314 -42.27019346 -17.75933714]
 [ 40.18212651   9.11044482  18.55053136]
 [ 10.70982625  39.71528055  21.45068983]
 [ 10.56872583  13.92983571 -10.67800354]]
save target mni to native space
1
load dicom E:\Test_data_set\S31\S31_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183026_363
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183026_363\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183026_363\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183026_363\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result
Show volume rendering of node Node_2
Show volume rendering of node Volume_1


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183026_363\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183026_363\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183026_363\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[ 10.34714192 -27.93393739 -45.05264526]
 [ 37.70552437  27.39599395  -3.77764217]
 [ 10.19682935  50.45328488  -2.85349776]
 [ 12.76635616  27.72149629 -34.7697205 ]]
save target mni to native space
2
load dicom E:\Test_data_set\S32\S32_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183100_359
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183100_359\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183100_359\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183100_359\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result_1
Show volume rendering of node Node_3
Show volume rendering of node Volume_2


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183100_359\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183100_359\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183100_359\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[ -3.30924264 -31.46071383 -30.7518365 ]
 [ 32.4841586    6.58170535   3.72766488]
 [  1.77012999  35.93724886   7.86797933]
 [  4.90114334  12.70754263 -20.98655842]]
save target mni to native space
3
load dicom E:\Test_data_set\S33\S33_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183134_163
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183134_163\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183134_163\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183134_163\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result_2
Show volume rendering of node Node_4
Show volume rendering of node Volume_3


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183134_163\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183134_163\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183134_163\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[  8.49509864 -44.89116022 -45.4419588 ]
 [ 35.4074094    7.50528092 -17.41566775]
 [  8.60207675  35.42742164 -21.54013346]
 [ 15.22260276   8.18756852 -39.20701388]]
save target mni to native space
4
load dicom E:\Test_data_set\S35\S35_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183205_770
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183205_770\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183205_770\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183205_770\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result_3
Show volume rendering of node Node_5
Show volume rendering of node Volume_4


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183205_770\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183205_770\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183205_770\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[  2.76963541 -35.9518461  -18.75219496]
 [ 30.82932508  14.09053786  12.41149413]
 [  5.01521898  44.08725463  11.63343385]
 [  9.65354467  14.46577768 -17.71667213]]
save target mni to native space
5
load dicom E:\Test_data_set\S36\S36_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183239_018
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183239_018\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183239_018\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183239_018\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result_4
Show volume rendering of node Node_6
Show volume rendering of node Volume_5


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183239_018\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183239_018\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183239_018\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[ 10.80725126 -22.66044289 -26.49405143]
 [ 41.07000079  33.20901371  18.44923327]
 [  6.57710494  55.58894473  20.3975423 ]
 [ 13.35003323  33.39912722  -8.83714149]]
save target mni to native space
6
load dicom E:\Test_data_set\S38\S38_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183313_561
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183313_561\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183313_561\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183313_561\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result_5
Show volume rendering of node Node_7
Show volume rendering of node Volume_6


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183313_561\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183313_561\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183313_561\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[  3.83406496 -51.93301335 -17.01967214]
 [ 31.7562982    2.69261129   9.97068329]
 [  5.12176503  25.75019766   6.94748001]
 [ 10.01968581  -1.13501698 -12.93929663]]
save target mni to native space
7
load dicom E:\Test_data_set\S39\S39_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183345_783
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183345_783\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183345_783\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183345_783\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result_6
Show volume rendering of node Node_8
Show volume rendering of node Volume_7


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183345_783\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183345_783\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183345_783\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[ 10.84437177 -36.8558092  -22.76179254]
 [ 45.17567342  10.49970092  13.29122154]
 [ 14.41532138  38.05899812  16.17310829]
 [ 18.43250065  12.44462083 -15.11723157]]
save target mni to native space
8
load dicom E:\Test_data_set\S42\S42_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183419_680
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183419_680\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183419_680\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183419_680\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result_7
Show volume rendering of node Node_9
Show volume rendering of node Volume_8


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183419_680\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183419_680\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183419_680\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[  9.17869687 -45.5386246  -39.41503158]
 [ 41.69781576   8.79849868 -12.43879263]
 [ 12.56619524  33.06836423 -16.44863203]
 [ 16.41836422   3.62737882 -40.78943405]]
save target mni to native space
9
load dicom E:\Test_data_set\S43\S43_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183452_416
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183452_416\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183452_416\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183452_416\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result_8
Show volume rendering of node Node_10
Show volume rendering of node Volume_9


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183452_416\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183452_416\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183452_416\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[  8.9337582  -17.79317371 -40.92586449]
 [ 39.24457809  28.19902122   5.16204333]
 [  9.78904381  49.13080474  12.56810182]
 [ 15.15634952  33.17996828 -24.4428432 ]]
save target mni to native space
10
load dicom E:\Test_data_set\S44\S44_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183526_791
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183526_791\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183526_791\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183526_791\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result_9
Show volume rendering of node Node_11
Show volume rendering of node Volume_10


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183526_791\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183526_791\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183526_791\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[ 11.24905854 -18.54334898 -56.07296394]
 [ 31.79043249  37.27273216  -3.02908703]
 [  1.93865904  56.89984708  -1.71797857]
 [ 12.64299923  37.48545986 -42.3561026 ]]
save target mni to native space
11
load dicom E:\Test_data_set\S46\S46_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183558_974
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183558_974\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183558_974\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183558_974\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result_10
Show volume rendering of node Node_12
Show volume rendering of node Volume_11


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183558_974\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183558_974\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183558_974\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[  6.65439575 -38.79630694 -38.39753098]
 [ 36.88770543   8.39594841  -1.83669085]
 [  6.55814112  33.61645835   1.48039608]
 [ 12.31587086   9.88274053 -29.37848889]]
save target mni to native space
12
load dicom E:\Test_data_set\S47\S47_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183632_763
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183632_763\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183632_763\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183632_763\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result_11
Show volume rendering of node Node_13
Show volume rendering of node Volume_12


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183632_763\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183632_763\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183632_763\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[  9.76004397 -29.36279481 -20.92896449]
 [ 32.93532013  21.37480763   5.20645479]
 [  0.97180018  40.72780762   0.99440755]
 [  9.64405083  19.57216248 -21.7911305 ]]
save target mni to native space
13
load dicom E:\Test_data_set\S51\51_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183706_866
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183706_866\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183706_866\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183706_866\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result_12
Show volume rendering of node Node_14
Show volume rendering of node Volume_13


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183706_866\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183706_866\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183706_866\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[ 10.2324636  -39.31493971  26.53833428]
 [ 41.73096134   5.49393132  61.94117066]
 [ 13.9035842   32.59384134  62.13492873]
 [ 18.68707531  11.66728183  35.79847634]]
save target mni to native space
14
load dicom E:\Test_data_set\S54\54_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183742_691
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183742_691\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183742_691\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183742_691\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result_13
Show volume rendering of node Node_15
Show volume rendering of node Volume_14


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183742_691\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183742_691\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183742_691\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[  6.79725549 -40.67563175  30.810946  ]
 [ 40.33094022   6.16709733  70.4129766 ]
 [ 11.09123469  36.00106724  70.99903038]
 [ 15.65785771  11.80915397  39.85612988]]
save target mni to native space
15
load dicom E:\Test_data_set\S55\55_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183817_611
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183817_611\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183817_611\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183817_611\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result_14
Show volume rendering of node Node_16
Show volume rendering of node Volume_15


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183817_611\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183817_611\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183817_611\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[  2.41751884 -47.33490549  46.52314124]
 [ 32.88383481   4.59215623  68.15171532]
 [  4.18460517  30.65485451  68.30166297]
 [  9.91555059   4.42421895  47.40993443]]
save target mni to native space
16
load dicom E:\Test_data_set\S56\56_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183846_845
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183846_845\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183846_845\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183846_845\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result_15
Show volume rendering of node Node_17
Show volume rendering of node Volume_16


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183846_845\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183846_845\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183846_845\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[  6.027796   -39.03546022  36.33074429]
 [ 29.92025498  16.79112914  67.06258867]
 [ -2.12100196  38.07362342  68.35035355]
 [  8.39586659  17.37620667  37.48943598]]
save target mni to native space
17
load dicom E:\Test_data_set\S57\57_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183920_712
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183920_712\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183920_712\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183920_712\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result_16
Show volume rendering of node Node_18
Show volume rendering of node Volume_17


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183920_712\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183920_712\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183920_712\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[ 12.78786387 -35.53464033  42.98322056]
 [ 40.50847927  15.68824192  74.47041281]
 [  3.32701757  34.96124057  74.39932175]
 [ 13.02560621  15.44370074  47.983141  ]]
save target mni to native space
18
load dicom E:\Test_data_set\S58\58_crop_T1.nii
push image to volumenode
Volume registration is started in working directory: C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183953_594
Register volumes...


toVTKString is deprecated! Conversion is no longer necessary.


Register volumes using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\elastix.exe: ['-f', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183953_594\\input\\fixed.mha', '-m', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183953_594\\input\\moving.mha', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183953_594\\result-transform', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_Rigid.txt', '-p', 'C:\\Users\\User\\AppData\\Roaming\\NA-MIC\\Extensions-29402\\SlicerElastix\\lib\\Slicer-4.11\\qt-scripted-modules\\Resources\\RegistrationParameters\\Parameters_BSpline.txt']
Show volume rendering of node result_17
Show volume rendering of node Node_19
Show volume rendering of node Volume_18


Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 13, in <lambda>
    qt.QTimer.singleShot(10, lambda: showVolumeRendering(node))
  File "C:/Users/User/AppData/Roaming/NA-MIC/Extensions-29402/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/.slicerrc.py", line 20, in showVolumeRendering
    scalarRange = volumeNode.GetImageData().GetScalarRange()
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'


Generate output...
Generate output using: C:\Users\User\AppData\Roaming\NA-MIC\Extensions-29402\SlicerElastix\lib\Slicer-4.11\transformix.exe: ['-tp', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183953_594\\result-transform/TransformParameters.1.txt', '-out', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183953_594\\result-resample', '-in', 'C:/Users/User/AppData/Local/Temp/Slicer/Elastix/20211206_183953_594\\input\\moving.mha', '-def', 'all']


loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.


Registration is completed
mni-registration
[[  8.82149579 -43.20634308  24.26274907]
 [ 38.34328711   3.96805258  62.55022157]
 [  5.20734297  31.66730641  59.83747671]
 [ 14.39446405   7.37188521  30.36956673]]
save target mni to native space
Show volume rendering of node result_18


In [13]:
scene = slicer.mrmlScene
sub_path_list = sorted(glob.glob(os.path.join(root_dir, 'S*')))
print(len(sub_path_list))
i=0

mni_image = load_nii(mni_path)
MNI_node = su.PushVolumeToSlicer(mni_image)

for sub_path in sub_path_list:
    try:
        sub_name = sub_path.split("\\")[-1].split("_")[0]
       
        print(i)
        i+=1

        T1_path = glob.glob(os.path.join(sub_path, '*crop_T1.nii'))[0]
        T1_image = load_nii(T1_path)
        print('load dicom', T1_path) 

        #sitk image to VolumeNode
        T1_node = su.PushVolumeToSlicer(T1_image)
        print('push image to volumenode')

        MNI_registeredNode, MNI_transformNode = registration_elastix(T1_node , MNI_node)
        print('mni-registration')
        
        target_np = TransformMarkups(MNI_transformNode)

        sub_name = sub_path.split("\\")[-1].split("_")[0]
        save_path = os.path.join(sub_path)

        if not os.path.exists(save_path):
            os.makedirs(save_path)
            print(save_path)
            
            
        V1 = str('{:.3f}'.format(target_np[0][0]) + ' {:.3f}'.format(target_np[0][1]) + ' {:.3f}'.format(target_np[0][2]))
        f = open(os.path.join(save_path, 'target_V1_MNI.txt'), 'w')
        f.write(V1)
        f.close()
               
        M1 = str('{:.3f}'.format(target_np[1][0]) + ' {:.3f}'.format(target_np[1][1]) + ' {:.3f}'.format(target_np[1][2]))
        f = open(os.path.join(save_path, 'target_M1_MNI.txt'), 'w')
        f.write(M1)

        
        Dorsal_ACC = str('{:.3f}'.format(target_np[2][0]) + ' {:.3f}'.format(target_np[2][1]) + ' {:.3f}'.format(target_np[2][2]))
        f = open(os.path.join(save_path, 'target_DorsalACCUp5.txt'), 'w')
        f.write(Dorsal_ACC)
        f.close()
        
        print('save target mni to native space')

        #clear

        slicer.mrmlScene.RemoveNode(T1_node)
        slicer.mrmlScene.RemoveNode(MNI_transformNode)
        slicer.mrmlScene.RemoveNode(MNI_registeredNode)
        
        
    except Exception as e: 
        print(e)
        print(sub_path, 'wrong')
        continue

19


RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: D:\D\S\Slicer-0-build\ITK\Modules\IO\NIFTI\src\itkNiftiImageIO.cxx:1025:
itk::ERROR: itk::ERROR: NiftiImageIO(000001B76805B2B0): C:\Users\User\AppData\Local\NA-MIC\Slicer 4.11.20200930\mni_icbm152_t1_tal_nlin_asym_09a.nii is not recognized as a NIFTI file

Show volume rendering of node mni_icbm152_t1_tal_nlin_asym_09a


In [ ]:
mni_icbm152_t1_tal_nlin_asym_09a.nii